# Generated by Django 6.0.4 on 2026-04-19 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul Novel')),
                ('author', models.CharField(max_length=255, verbose_name='Penulis')),
                ('genre', models.CharField(choices=[('fantasy', 'Fantasy'), ('sci_fi', 'Sci-Fi'), ('romance', 'Romance'), ('misteri', 'Misteri'), ('thriller', 'Thriller'), ('horror', 'Horror'), ('historical', 'Historical Fiction'), ('literary', 'Literary Fiction'), ('adventure', 'Adventure'), ('dystopia', 'Dystopia'), ('biography', 'Biografi'), ('other', 'Lainnya')], default='other', max_length=50, verbose_name='Genre')),
                ('review', models.TextField(verbose_name='Review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
